remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: Riccardo Taiello
description: Ph.D. student at Inria Sophia Antipolis, Epione group.
show_downloads: false
logo: https://github.com/rtaiello.png?size=420
github: [metadata]
color-scheme: auto
