remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
title: Andrea Bacciu
description: Artificial Intelligence PhD's student in Natural Language Processing at Sapienza University of Rome. Ex-Google DSC Lead in 2019/2020.
show_downloads: false
logo: "/assets/data/IMG_3376.jpeg" #https://github.com/andreabac3.png?size=256
github: [metadata]
color-scheme: auto
